### PR TITLE
Add graph index information

### PR DESCRIPTION
**Pull request by ifavo**
This PR adds a new section explaining how to index data using graph nodes.

### CODE REVIEW

**Review by fabiorigam — COMMENTED** [review]
LGTM! Just update also the README.md inside the developer-resources with the new item`(developer-resources/README.md)`

**Review by nwbrettski — APPROVED** [review]
LGTM. Great contribution. Look forward to seeing more adoption subgraphs.

**Comment by ifavo** [comment]
> LGTM! Just update also the README.md inside the developer-resources with the new item`developer-resources/README.md`

 🙏 I've added a line in the file

**Comment by ifavo** [comment]
> LGTM. Great contribution. Look forward to seeing more adoption subgraphs.

Thank you 🙏  Would love to provide more examples, the https://github.com/vechain-energy/subgraph-vebetter-dao is already a first initiate for a more complex public one :)

**Review by fabiorigam — APPROVED** [review]

**Pull request merged**
